// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcmVm79MayAi_Twl_fuPpVX4zthzuLtrc',
    appId: '1:483176079785:web:e8133e234453bbb59f64b8',
    messagingSenderId: '483176079785',
    projectId: 'e-learning-platform-fd30c',
    authDomain: 'e-learning-platform-fd30c.firebaseapp.com',
    storageBucket: 'e-learning-platform-fd30c.firebasestorage.app',
    measurementId: 'G-ENHVD7H3M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVYNfNuFtp-x6MpJ7tXCoPmXCnCjexAg',
    appId: '1:483176079785:android:fa0088d10df7410b9f64b8',
    messagingSenderId: '483176079785',
    projectId: 'e-learning-platform-fd30c',
    storageBucket: 'e-learning-platform-fd30c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyM8FUcC5v6GtJHe8hQM9L6lx_bpZ3D8k',
    appId: '1:483176079785:ios:8dab173292e550629f64b8',
    messagingSenderId: '483176079785',
    projectId: 'e-learning-platform-fd30c',
    storageBucket: 'e-learning-platform-fd30c.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyM8FUcC5v6GtJHe8hQM9L6lx_bpZ3D8k',
    appId: '1:483176079785:ios:8dab173292e550629f64b8',
    messagingSenderId: '483176079785',
    projectId: 'e-learning-platform-fd30c',
    storageBucket: 'e-learning-platform-fd30c.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcmVm79MayAi_Twl_fuPpVX4zthzuLtrc',
    appId: '1:483176079785:web:61c1eadaea5e5de19f64b8',
    messagingSenderId: '483176079785',
    projectId: 'e-learning-platform-fd30c',
    authDomain: 'e-learning-platform-fd30c.firebaseapp.com',
    storageBucket: 'e-learning-platform-fd30c.firebasestorage.app',
    measurementId: 'G-4ZYEPSXRC9',
  );
}
